# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.CharField(max_length=50),
        ),
    ]
