# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161104_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_off', models.DateTimeField(auto_now_add=True)),
                ('pick_up', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='in_class',
        ),
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.BooleanField(choices=[('In', True), ('Out', False)], default=False),
        ),
        migrations.AddField(
            model_name='checkin_log',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Child'),
        ),
    ]
