# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161107_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='status',
        ),
        migrations.AlterField(
            model_name='checkin_log',
            name='pick_up',
            field=models.DateTimeField(null=True),
        ),
    ]
