# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161107_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin_log',
            options={'ordering': ('-drop_off',)},
        ),
        migrations.AlterField(
            model_name='child',
            name='pin',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
